
export enum UserServiceEventEnum {
    GET_DATA_FROM_QUIZ = "GET_DATA_FROM_QUIZ",
    SUBSCRIBER_NEW = "SUBSCRIBER_NEW",
    SUBSCRIBER_PLAN_EXPIRY_DATE_UPDATE = "SUBSCRIBER_PLAN_EXPIRY_DATE_UPDATE",
    RENEWAL_DONE_PLAN_SAME = "RENEWAL_DONE_PLAN_SAME",
    RENEWAL_DONE_PLAN_CHANGE = "RENEWAL_DONE_PLAN_CHANGE",
    POST_NEW_PLAN_CREATION = "POST_NEW_PLAN_CREATION",
    DIGIT_WEBHOOK_CLAIM_STATUS_CHECK = "DIGIT_WEBHOOK_CLAIM_STATUS_CHECK",

}