export enum AvailabilityTypeEnum {
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE',
  NOTREQUIRED = 'NOTREQUIRED',
  CONFIRMED_ITEM = 'CONFIMREDITEM',
}

export enum MarketPlaceServiceQueueEventEnum {
  PLACE_ORDER = 'PLACE_ORDER',
  PLACE_ORDER_POST_PROCESSING = 'PLACE_ORDER_POST_PROCESSING',
  CANCEL_ORDER = 'CANCEL_ORDER',
  CONFIRM_ORDER = 'CONFIRM_ORDER',
  CONFIRM_PAYMENT = 'CONFIRM_PAYMENT',
  UPDATE_ORDER = 'UPDATE_ORDER',

  WEBHOOK_CREATED = 'WEBHOOK_CREATED',
  WEBHOOK_ACCEPTED = 'WEBHOOK_ACCEPTED',
  WEBHOOK_INVOICEGENERATED = 'WEBHOOK_INVOICEGENERATED',
  WEBHOOK_OUTFORDELIVERY = 'WEBHOOK_OUTFORDELIVERY',
  WEBHOOK_DELIVERED = 'WEBHOOK_DELIVERED',
  WEBHOOK_MODIFIED = 'WEBHOOK_MODIFIED',
  WEBHOOK_CANCELLED = 'WEBHOOK_CANCELLED',

  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
  ZOHO_INVOICE_PAID = 'ZOHO_INVOICE_PAID',
}

export enum CouponTypeEnum {
  ONE_TIME_PERCENT_DISCOUNT = 'ONE_TIME_PERCENT_DISCOUNT',
  ONE_TIME_ABSOLUTE_DISCOUNT = 'ONE_TIME_ABSOLUTE_DISCOUNT',
  SINGLE_USE_COUPON = 'SINGLE_USE_COUPON',
}

export enum OrderIssues {
  MISSING = 'MISSING',
  DAMAGED = 'DAMAGED',
  EXPIRED = 'EXPIRED',
  WRONG_ITEM = 'WRONG_ITEM',
  OTHERS = 'OTHERS',
}
