

//events emitted from scheduler service
export enum SchedulerServiceEventEnum {
    SCHEDULED_RENEWAL_NOTIFICATION = "SCHEDULED_RENEWAL_NOTIFICATION",
    PLAN_PHASE_TRANSITION = "PLAN_PHASE_TRANSITION",
    FUTURE_PLAN_CHANGE = "FUTURE_PLAN_CHANGE",
    DIAGNOSTIC_STATUS_UPDATE = "DIAGNOSTIC_STATUS_UPDATE",
    DIGIT_WEBHOOK_CLAIM_STATUS_CHECK = "DIGIT_WEBHOOK_CLAIM_STATUS_CHECK",
}


export enum PlanPhaseEnum {
    NORMAL = "NORMAL",
    RENEWAL = "RENEWAL",
    GRACE = "GRACE",
    POST_GRACE = "POST_GRACE",
    EXPIRY = "EXPIRY",
    POST_EXPIRY = "POST_EXPIRY",
}
