export enum MarketplaceConsumerEvents {
  MARKETPLACE_POTENTIAL_ORDER = 'MARKETPLACE_POTENTIAL_ORDER',
  MARKETPLACE_CART_MODIFICATION = 'MARKETPLACE_CART_MODIFICATION',
  MARKETPLACE_ORDER_PLACED = 'MARKETPLACE_ORDER_PLACED',
  MARKETPLACE_ORDER_MODIFICATION = 'MARKETPLACE_ORDER_MODIFICATION',
  MARKETPLACE_INVOICE_GENERATED = 'MARKETPLACE_INVOICE_GENERATED',
  MARKETPLACE_ORDER_CONFIRMATION = 'MARKETPLACE_ORDER_CONFIRMATION',
  MARKETPLACE_ORDER_SHIPPED = 'MARKETPLACE_ORDER_SHIPPED',
  MARKETPLACE_ORDER_OUT_FOR_DELIVERY = 'MARKETPLACE_ORDER_OUT_FOR_DELIVERY',
  MARKETPLACE_ORDER_FULFILLED = 'MARKETPLACE_ORDER_FULFILLED',
  MARKETPLACE_ORDER_CANCELLED = 'MARKETPLACE_ORDER_CANCELLED',
  MARKETPLACE_ORDER_CANCELLED_BY_PARTNER = 'MARKETPLACE_ORDER_CANCELLED_BY_PARTNER',
  MARKETPLACE_ORDER_REJECTED = 'MARKETPLACE_ORDER_REJECTED',
  MARKETPLACE_PROCESSED = 'MARKETPLACE_PROCESSED',
  MARKETPLACE_WAITING_FOR_APPROVAL = 'MARKETPLACE_WAITING_FOR_APPROVAL',
  MARKETPLACE_ORDER_ESCALATE = 'MARKETPLACE_ORDER_ESCALATE',
}

export const MARKETPLACE_ORDER_TYPE = 'Marketplace Order';
