



//events emitted from payment service
export enum PaymentServiceEventEnum {
    PAYMENT_MADE = "PAYMENT_MADE",
    RENEWAL_LINK_READY = "RENEWAL_LINK_READY",
    ZOHO_CUSTOMER_ID_UPDATE = "ZOHO_CUSTOMER_ID_UPDATE",
    POST_ZOHO_INVOICE_CREATION = "POST_ZOHO_INVOICE_CREATION",
    ZOHO_PAYMENT_WEBHOOK = "ZOHO_PAYMENT_WEBHOOK",
    INVOICE_UNIQUE_LINK = "INVOICE_UNIQUE_LINK",
}



export enum PaymentEntityEnum {
    PLAN_PURCHASE = "PLAN_PURCHASE",
    PLAN_PURCHASE_VIA_MANDATE = "PLAN_PURCHASE_VIA_MANDATE",
    // PAYMENT_DONE = "PAYMENT_DONE",
    // PAYMENT_DONE_UPI = "PAYMENT_DONE_UPI",
    RENEWAL_DONE_WITH_PLAN_SAME = 'RENEWAL_DONE_WITH_PLAN_SAME',
    RENEWAL_DONE_WITH_PLAN_CHANGE = 'RENEWAL_DONE_WITH_PLAN_CHANGE'
}


export enum PaymentMediumEnum {
    UPI_MANDATE = 'UPI_MANDATE',
    STAND_ALONE_INVOICE = 'STAND_ALONE_INVOICE' //covers both case : plan change or duration change
}